"""
Production QA question matrices — Wave 2 (Finance/Ops/Support) and Wave 3 (HR/Healthcare).

Wave 1 specs remain in wave1_qa_execution.build_domain_specs().
"""

from __future__ import annotations

from typing import Any, Dict

from wave1_qa_execution import ChainSpec, QuestionSpec


def build_wave2_specs() -> Dict[str, Dict[str, Any]]:
    """Finance / FP&A, Operations, Customer Support."""
    return {
        "Finance & FP&A": {
            "file": "finance_fpa.csv",
            "questions": [
                QuestionSpec(
                    "F2-B01",
                    "Which department has the largest budget variance?",
                    "ranking",
                    ("ranking", "compare"),
                    ("bar",),
                    "variance",
                    "department",
                    ground_fn="ranking",
                ),
                QuestionSpec(
                    "F2-B02",
                    "Compare actual spend across cost centers",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "actual",
                    "cost_center",
                ),
                QuestionSpec(
                    "F2-B03",
                    "Show revenue trend over report date",
                    "trend",
                    ("trend",),
                    ("line", "area"),
                    "revenue",
                    "report_date",
                ),
                QuestionSpec(
                    "F2-B04",
                    "Rank categories by actual cost",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "cost",
                    "category",
                ),
                QuestionSpec(
                    "F2-I01",
                    "Compare budget vs actual by department",
                    "compare",
                    ("compare",),
                    ("bar", "groupedbar"),
                    "budget",
                    "department",
                ),
                QuestionSpec(
                    "F2-I02",
                    "Is revenue correlated with units?",
                    "relationship",
                    ("relationship",),
                    ("scatter",),
                    "revenue",
                    "units",
                ),
                QuestionSpec(
                    "F2-E01",
                    "What are the biggest FP&A risks?",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "variance",
                    "department",
                ),
                QuestionSpec(
                    "F2-E02",
                    "Where is cost overrun concentrated?",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "actual",
                    "department",
                ),
                QuestionSpec(
                    "F2-E03",
                    "Executive summary of department performance",
                    "summary",
                    ("summary", "executive"),
                    ("bar",),
                    "revenue",
                    "department",
                ),
                QuestionSpec(
                    "F2-NEG",
                    "Compare EBITDA margin trend by quarter",
                    "negative",
                    ("fallback", "unsupported"),
                    ("none",),
                    "ebitda",
                    "quarter",
                    negative=True,
                ),
                QuestionSpec(
                    "F2-I03",
                    "Which cost center exceeds budget the most?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "variance",
                    "cost_center",
                ),
                QuestionSpec(
                    "F2-D01",
                    "Variance analysis by category",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "variance",
                    "category",
                ),
            ],
            "chains": [
                ChainSpec(
                    "F2-C1",
                    QuestionSpec(
                        "F2-C1-Q",
                        "Which department has the largest budget variance?",
                        "ranking",
                        ("ranking",),
                        ("bar",),
                        "variance",
                        "department",
                        ground_fn="ranking",
                    ),
                    [
                        "Why is {ENTITY} highest?",
                        "Which columns were used for this analysis?",
                        "Show the calculations behind this answer.",
                    ],
                ),
            ],
        },
        "Operations": {
            "file": "operations.csv",
            "questions": [
                QuestionSpec(
                    "O2-B01",
                    "Which facility has the highest downtime hours?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "downtime",
                    "facility",
                    ground_fn="ranking",
                ),
                QuestionSpec(
                    "O2-B02",
                    "Compare defect rate across production lines",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "defect",
                    "production_line",
                ),
                QuestionSpec(
                    "O2-B03",
                    "Show units produced trend over time",
                    "trend",
                    ("trend",),
                    ("line", "area"),
                    "units_produced",
                    "report_date",
                ),
                QuestionSpec(
                    "O2-B04",
                    "Rank shifts by SLA score",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "sla",
                    "shift",
                ),
                QuestionSpec(
                    "O2-I01",
                    "Is downtime correlated with defect rate?",
                    "relationship",
                    ("relationship",),
                    ("scatter",),
                    "downtime",
                    "defect",
                ),
                QuestionSpec(
                    "O2-I02",
                    "Which department has the lowest SLA score?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "sla",
                    "department",
                ),
                QuestionSpec(
                    "O2-E01",
                    "What are the biggest operational risks?",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "downtime",
                    "facility",
                ),
                QuestionSpec(
                    "O2-E02",
                    "Where is production loss concentrated?",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "cost",
                    "facility",
                ),
                QuestionSpec(
                    "O2-E03",
                    "Executive summary of plant performance",
                    "summary",
                    ("summary",),
                    ("bar",),
                    "units_produced",
                    "facility",
                ),
                QuestionSpec(
                    "O2-NEG",
                    "Compare OEE trend by quarter",
                    "negative",
                    ("fallback",),
                    ("none",),
                    "oee",
                    "quarter",
                    negative=True,
                ),
                QuestionSpec(
                    "O2-D01",
                    "Compare cost across facilities",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "cost",
                    "facility",
                ),
            ],
            "chains": [
                ChainSpec(
                    "O2-C1",
                    QuestionSpec(
                        "O2-C1-Q",
                        "Which facility has the highest downtime hours?",
                        "ranking",
                        ("ranking",),
                        ("bar",),
                        "downtime",
                        "facility",
                        ground_fn="ranking",
                    ),
                    [
                        "Why is {ENTITY} highest?",
                        "What evidence supports this conclusion?",
                        "Which columns were used for this analysis?",
                    ],
                ),
            ],
        },
        "Customer Support": {
            "file": "customer_support.csv",
            "questions": [
                QuestionSpec(
                    "C2-B01",
                    "Which ticket category has the longest resolution time?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "resolution",
                    "ticket_category",
                    ground_fn="ranking",
                ),
                QuestionSpec(
                    "C2-B02",
                    "Compare satisfaction score across channels",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "satisfaction",
                    "channel",
                ),
                QuestionSpec(
                    "C2-B03",
                    "Show tickets opened trend over report date",
                    "trend",
                    ("trend",),
                    ("line",),
                    "tickets_opened",
                    "report_date",
                ),
                QuestionSpec(
                    "C2-B04",
                    "Rank departments by escalation count",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "escalations",
                    "department",
                ),
                QuestionSpec(
                    "C2-I01",
                    "Compare tickets resolved vs opened by priority",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "tickets_resolved",
                    "priority",
                ),
                QuestionSpec(
                    "C2-I02",
                    "Is satisfaction correlated with resolution time?",
                    "relationship",
                    ("relationship",),
                    ("scatter",),
                    "satisfaction",
                    "resolution",
                ),
                QuestionSpec(
                    "C2-E01",
                    "What are the biggest support risks?",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "escalations",
                    "department",
                ),
                QuestionSpec(
                    "C2-E02",
                    "Biggest support opportunity for leadership",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "satisfaction",
                    "channel",
                ),
                QuestionSpec(
                    "C2-E03",
                    "Executive summary of support performance",
                    "summary",
                    ("summary",),
                    ("bar",),
                    "tickets_resolved",
                    "department",
                ),
                QuestionSpec(
                    "C2-NEG",
                    "Compare NPS across ticket categories",
                    "negative",
                    ("fallback",),
                    ("none",),
                    "nps",
                    "ticket_category",
                    negative=True,
                ),
                QuestionSpec(
                    "C2-D01",
                    "Which priority level drives the most escalations?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "escalations",
                    "priority",
                ),
            ],
            "chains": [
                ChainSpec(
                    "C2-C1",
                    QuestionSpec(
                        "C2-C1-Q",
                        "Which ticket category has the longest resolution time?",
                        "ranking",
                        ("ranking",),
                        ("bar",),
                        "resolution",
                        "ticket_category",
                        ground_fn="ranking",
                    ),
                    [
                        "Why is {ENTITY} highest?",
                        "Which columns were used for this analysis?",
                        "Show the calculations behind this answer.",
                    ],
                ),
            ],
        },
    }


def build_wave3_specs() -> Dict[str, Dict[str, Any]]:
    """HR and Healthcare."""
    return {
        "HR": {
            "file": "hr.csv",
            "questions": [
                QuestionSpec(
                    "H3-B01",
                    "Which department has the highest personnel cost?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "personnel_cost",
                    "department",
                    ground_fn="ranking",
                ),
                QuestionSpec(
                    "H3-B02",
                    "Compare attrition rate across locations",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "attrition",
                    "location",
                ),
                QuestionSpec(
                    "H3-B03",
                    "Show headcount trend over report date",
                    "trend",
                    ("trend",),
                    ("line",),
                    "headcount",
                    "report_date",
                ),
                QuestionSpec(
                    "H3-B04",
                    "Rank job families by satisfaction score",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "satisfaction",
                    "job_family",
                ),
                QuestionSpec(
                    "H3-I01",
                    "Compare hires vs terminations by department",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "hires",
                    "department",
                ),
                QuestionSpec(
                    "H3-I02",
                    "Is attrition correlated with satisfaction score?",
                    "relationship",
                    ("relationship",),
                    ("scatter",),
                    "attrition",
                    "satisfaction",
                ),
                QuestionSpec(
                    "H3-E01",
                    "What are the biggest workforce risks?",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "attrition",
                    "department",
                ),
                QuestionSpec(
                    "H3-E02",
                    "Biggest HR opportunity for leadership",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "headcount",
                    "location",
                ),
                QuestionSpec(
                    "H3-E03",
                    "Executive summary of workforce performance",
                    "summary",
                    ("summary",),
                    ("bar",),
                    "personnel_cost",
                    "department",
                ),
                QuestionSpec(
                    "H3-NEG",
                    "Compare employee engagement score by quarter",
                    "negative",
                    ("fallback",),
                    ("none",),
                    "engagement",
                    "quarter",
                    negative=True,
                ),
                QuestionSpec(
                    "H3-D01",
                    "Which location has the highest attrition rate?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "attrition",
                    "location",
                ),
            ],
            "chains": [
                ChainSpec(
                    "H3-C1",
                    QuestionSpec(
                        "H3-C1-Q",
                        "Which department has the highest personnel cost?",
                        "ranking",
                        ("ranking",),
                        ("bar",),
                        "personnel_cost",
                        "department",
                        ground_fn="ranking",
                    ),
                    [
                        "Why is {ENTITY} highest?",
                        "Which columns were used for this analysis?",
                        "Show the calculations behind this answer.",
                    ],
                ),
            ],
        },
        "Healthcare": {
            "file": "healthcare.csv",
            "questions": [
                QuestionSpec(
                    "HC3-B01",
                    "Which ward has the highest patient volume?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "patient_volume",
                    "ward",
                    ground_fn="ranking",
                ),
                QuestionSpec(
                    "HC3-B02",
                    "Compare readmissions across departments",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "readmissions",
                    "department",
                ),
                QuestionSpec(
                    "HC3-B03",
                    "Show admissions trend over report date",
                    "trend",
                    ("trend",),
                    ("line",),
                    "admissions",
                    "report_date",
                ),
                QuestionSpec(
                    "HC3-B04",
                    "Rank regions by average length of stay",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "length_of_stay",
                    "region",
                ),
                QuestionSpec(
                    "HC3-I01",
                    "Is cost correlated with patient volume?",
                    "relationship",
                    ("relationship",),
                    ("scatter",),
                    "cost",
                    "patient_volume",
                ),
                QuestionSpec(
                    "HC3-I02",
                    "Which department has the lowest satisfaction score?",
                    "ranking",
                    ("ranking",),
                    ("bar",),
                    "satisfaction",
                    "department",
                ),
                QuestionSpec(
                    "HC3-E01",
                    "What are the biggest clinical operational risks?",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "readmissions",
                    "department",
                ),
                QuestionSpec(
                    "HC3-E02",
                    "Where is patient volume overly concentrated?",
                    "executive",
                    ("executive",),
                    ("bar",),
                    "patient_volume",
                    "ward",
                ),
                QuestionSpec(
                    "HC3-E03",
                    "Executive summary of regional performance",
                    "summary",
                    ("summary",),
                    ("bar",),
                    "cost",
                    "region",
                ),
                QuestionSpec(
                    "HC3-NEG",
                    "Compare patient risk score across wards",
                    "negative",
                    ("fallback",),
                    ("none",),
                    "patient_risk",
                    "ward",
                    negative=True,
                ),
                QuestionSpec(
                    "HC3-D01",
                    "Compare satisfaction score across regions",
                    "compare",
                    ("compare",),
                    ("bar",),
                    "satisfaction",
                    "region",
                ),
            ],
            "chains": [
                ChainSpec(
                    "HC3-C1",
                    QuestionSpec(
                        "HC3-C1-Q",
                        "Which ward has the highest patient volume?",
                        "ranking",
                        ("ranking",),
                        ("bar",),
                        "patient_volume",
                        "ward",
                        ground_fn="ranking",
                    ),
                    [
                        "Why is {ENTITY} highest?",
                        "What evidence supports this conclusion?",
                        "Which columns were used for this analysis?",
                    ],
                ),
            ],
        },
    }


def build_all_wave_specs() -> Dict[int, Dict[str, Dict[str, Any]]]:
    from wave1_qa_execution import build_domain_specs

    return {
        1: build_domain_specs(),
        2: build_wave2_specs(),
        3: build_wave3_specs(),
    }
