import { describe, expect, it } from "vitest";
import {
  BRANDING,
  buildExportPdfFilename,
  buildPdfFooterCenterLine,
  buildPdfGeneratedByLine,
  buildPdfSupportLine,
  getBrandInitials,
  sanitizeExportFilePrefix,
} from "@/lib/branding-config";

describe("branding-config", () => {
  it("derives initials from short name", () => {
    expect(getBrandInitials("Analyst")).toBe("AN");
    expect(getBrandInitials("AI Data")).toBe("AD");
  });

  it("builds export pdf filename with prefix", () => {
    expect(buildExportPdfFilename("acme")).toBe("acme-analytics-report.pdf");
    expect(buildExportPdfFilename(BRANDING.exportFilePrefix)).toBe(
      "app-analytics-report.pdf"
    );
  });

  it("sanitizes export file prefix", () => {
    expect(sanitizeExportFilePrefix("My Brand!")).toBe("My-Brand");
  });

  it("builds pdf footer lines", () => {
    expect(buildPdfGeneratedByLine("Acme Analytics")).toBe(
      "Generated by Acme Analytics"
    );
    expect(buildPdfSupportLine("help@acme.com")).toBe("Support: help@acme.com");
  });

  it("uses custom pdfFooterText when set", () => {
    expect(
      buildPdfFooterCenterLine({
        ...BRANDING,
        pdfFooterText: "Confidential — internal use only",
      })
    ).toBe("Confidential — internal use only");
  });
});
