/**
 * Global V1 branding — edit this file to white-label the app.
 * No database, localStorage, or per-tenant overrides.
 */

export type BrandingConfig = {
  appName: string;
  shortName: string;
  supportEmail: string;
  primaryColor: string;
  secondaryColor: string;
  pdfFooterText: string;
  exportFilePrefix: string;
  logoUrl?: string;
  /** Optional sidebar badge, e.g. "V1". */
  version?: string;
};

export const BRANDING: BrandingConfig = {
  appName: "AI Data Analyst",
  shortName: "Analyst",
  supportEmail: "support@example.com",
  primaryColor: "#6366f1",
  secondaryColor: "#8b5cf6",
  pdfFooterText: "",
  exportFilePrefix: "app",
  logoUrl: undefined,
  version: "V1",
};

export function getBrandInitials(name: string = BRANDING.shortName): string {
  const trimmed = name.trim();
  if (!trimmed) return "AA";
  const words = trimmed.split(/\s+/).filter(Boolean);
  if (words.length >= 2) {
    return `${words[0][0] ?? ""}${words[1][0] ?? ""}`.toUpperCase();
  }
  return trimmed.slice(0, 2).toUpperCase();
}

export function sanitizeExportFilePrefix(raw: string): string {
  const t = raw.trim().slice(0, 48) || "analytics";
  return (
    t.replace(/[^a-zA-Z0-9-_]+/g, "-").replace(/^-+|-+$/g, "") || "analytics"
  );
}

/** Browser download filename for executive PDF exports. */
export function buildExportPdfFilename(
  prefix: string = BRANDING.exportFilePrefix
): string {
  return `${sanitizeExportFilePrefix(prefix)}-analytics-report.pdf`;
}

export function buildPdfGeneratedByLine(
  appName: string = BRANDING.appName
): string {
  return `Generated by ${appName}`;
}

export function buildPdfSupportLine(
  email: string = BRANDING.supportEmail
): string {
  return `Support: ${email}`;
}

/** Center footer line — custom pdfFooterText or default generated-by line. */
export function buildPdfFooterCenterLine(
  branding: BrandingConfig = BRANDING
): string {
  const custom = branding.pdfFooterText.trim();
  if (custom) return custom;
  return buildPdfGeneratedByLine(branding.appName);
}

export function brandingCssVariables(
  branding: BrandingConfig = BRANDING
): Record<string, string> {
  return {
    "--primary": branding.primaryColor,
    "--accent": branding.secondaryColor,
    "--accent-hover": branding.primaryColor,
  };
}

export const APP_METADATA = {
  title: BRANDING.appName,
  description: `Upload business data and explore it with ${BRANDING.appName}.`,
} as const;
