/**
 * Charts tab PNG — html2canvas cannot parse Tailwind v4 `color-mix()` / `color()` in app stylesheets.
 * Strategy: Canvg for the plot (sharp) + canvas 2D for title/chips (no html2canvas).
 */

import { Canvg } from "canvg";
import {
  readResolvedChartAxisTheme,
  type ResolvedChartAxisTheme,
} from "@/lib/chart-axis-theme";
import { ensureReadableExportTextFill } from "@/lib/chart-png-export-text";
import { applyPngExportSvgPolish } from "@/lib/chart-png-export-svg-polish";
import {
  RADIAL_EXPORT_FOOTER_FONT_PX,
  RADIAL_EXPORT_FOOTER_RESERVE_PX,
  RADIAL_EXPORT_LEGEND_FONT_PX,
  RADIAL_EXPORT_LEGEND_ICON_PX,
  RADIAL_EXPORT_LEGEND_ITEM_GAP_PX,
  RADIAL_EXPORT_LEGEND_PLOT_GAP_PX,
  RADIAL_EXPORT_LEGEND_ROW_EXTRA_PX,
  RADIAL_EXPORT_LEGEND_SWATCH_GAP_PX,
  RADIAL_EXPORT_MIN_SVG_PAD_PX,
  RADIAL_EXPORT_PLOT_BAND_DIAMETER_RATIO,
  RADIAL_EXPORT_PLOT_WIDTH_UTIL,
} from "@/lib/radial-export-layout";
const EXPORT_MIN_WIDTH = 720;
/** Plot uses most of the inner card width without stretching sparse bar SVGs. */
const PLOT_WIDTH_UTIL = 0.97;
const PLOT_WIDTH_UTIL_COMPACT = 0.99;
const COMPOSITE_PAD_X = 16;
const COMPOSITE_PAD_Y = 8;
const HEADER_PLOT_GAP = 8;
/** Export-only inner card padding (visible UI unchanged). */
const EXPORT_CARD_PAD = 28;
const EXPORT_CARD_RADIUS = 18;
const EXPORT_CARD_BORDER = 2;
const EXPORT_FOOTER_H = 34;
const EXPORT_FOOTER_PAD_BOTTOM = 14;
const EXPORT_FOOTER_FONT_PX = 15;
const EXPORT_FOOTER_TEXT = "Generated by AI Analytics";

const HEADER_PAD_Y = 14;
const GAP_AFTER_KICKER = 3;
const GAP_AFTER_TITLE = 4;
const GAP_AFTER_TITLE_WITH_CHIPS = 12;
const GAP_AFTER_SUBTITLE = 5;
const GAP_AFTER_CHIPS = 8;
const CHIP_ROW_GAP = 5;
// Overview summary chips in PNG ("Top / Lowest / Gap") look cramped at default gap.
// Only used for the PNG header render (not on-screen layout).
const OVERVIEW_SUMMARY_CHIP_ROW_GAP = 14;
const CHIP_H = 36;
const CHIP_PAD_X = 14;
const CHIP_INNER_GAP = 5;
const CHIP_VALUE_FONT_SIZE_PX = 16;
const CHIP_LABEL_FONT_SIZE_PX = 15;
const QUALITY_WARNING_FONT_SIZE_PX = 12;
const REASON_LABEL_LINE_H = 12;
const REASON_LABEL_BODY_GAP = 4;
const REASON_LINE_H = 17;
const REASON_BOTTOM_PAD = 10;

type ExportPalette = {
  background: string;
  title: string;
  subtitle: string;
  kicker: string;
  warningNote: string;
  chipBorder: string;
  chipLabel: string;
  chipValue: string;
  chipBg: string;
  reason: string;
  footer: string;
};

function resolveExportPalette(backgroundColor?: string): ExportPalette {
  const dark =
    backgroundColor === "#0f172a" ||
    backgroundColor === "#0b1220" ||
    (typeof document !== "undefined" &&
      !backgroundColor &&
      document.documentElement.classList.contains("dark"));

  if (dark) {
    return {
      background: backgroundColor ?? "#0f172a",
      title: "#f8fafc",
      subtitle: "#94a3b8",
      kicker: "#64748b",
      warningNote: "#94a3b8",
      chipBorder: "#475569",
      chipLabel: "#94a3b8",
      chipValue: "#f1f5f9",
      chipBg: "#1e293b",
      reason: "#94a3b8",
      footer: "#b8c8dc",
    };
  }
  return {
    background: backgroundColor ?? "#ffffff",
    title: "#0f172a",
    subtitle: "#475569",
    kicker: "#64748b",
    warningNote: "#475569",
    chipBorder: "#cbd5e1",
    chipLabel: "#475569",
    chipValue: "#0f172a",
    chipBg: "#f1f5f9",
    reason: "#475569",
    footer: "#64748b",
  };
}

function isDarkExportBackground(background: string): boolean {
  return (
    background === "#0f172a" ||
    background === "#0b1220" ||
    (typeof document !== "undefined" &&
      document.documentElement.classList.contains("dark"))
  );
}

function resolveExportBackground(optionsBg?: string): string {
  if (optionsBg) return optionsBg;
  if (typeof document === "undefined") return "#ffffff";
  return document.documentElement.classList.contains("dark") ? "#0f172a" : "#ffffff";
}

function isUnsafeCssColor(value: string): boolean {
  return /color-mix\s*\(|color\s*\(/i.test(value);
}

function resolveCssColorForExport(value: string): string {
  const v = value.trim();
  if (!v || v === "none" || v === "transparent") return v;
  if (!isUnsafeCssColor(v)) return v;

  if (typeof document === "undefined") return "#334155";

  const probe = document.createElement("span");
  probe.style.cssText =
    "position:fixed;left:-9999px;top:0;visibility:hidden;pointer-events:none;";
  probe.style.color = v;
  document.body.appendChild(probe);
  const resolved = window.getComputedStyle(probe).color;
  probe.remove();
  if (resolved && !isUnsafeCssColor(resolved)) return resolved;
  return "#334155";
}

function resolvePlotRoot(container: HTMLElement): HTMLElement {
  const selectors = [
    ".overview-chart-plot-inner .recharts-responsive-container",
    ".overview-chart-plot-inner .recharts-wrapper",
    ".overview-chart-plot .recharts-responsive-container",
    ".charts-tab-viz-plot-stage .recharts-responsive-container",
    ".charts-tab-viz-plot-stage .recharts-wrapper",
    ".ai-insights-viz-plot .recharts-responsive-container",
    ".recharts-responsive-container",
    ".recharts-wrapper",
  ];
  for (const sel of selectors) {
    const el = container.querySelector(sel);
    if (el instanceof HTMLElement) return el;
  }
  const plotStage =
    container.querySelector(".charts-tab-viz-plot-stage") ??
    container.querySelector(".overview-chart-plot-inner");
  if (plotStage instanceof HTMLElement) return plotStage;
  return container;
}

function findPrimaryChartSvg(root: HTMLElement): SVGSVGElement | null {
  const svgs = [...root.querySelectorAll("svg")].filter(
    (s): s is SVGSVGElement => s instanceof SVGSVGElement
  );
  if (!svgs.length) return null;
  let best = svgs[0]!;
  let bestArea = 0;
  for (const svg of svgs) {
    const r = svg.getBoundingClientRect();
    const area = r.width * r.height;
    if (area > bestArea) {
      bestArea = area;
      best = svg;
    }
  }
  return bestArea > 4 ? best : svgs[0] ?? null;
}

function isSvgAxisTitleText(src: Element): boolean {
  if (src.classList.contains("recharts-label")) return true;
  const parent = src.parentElement;
  if (parent?.classList.contains("recharts-label")) return true;
  if (!parent?.closest(".recharts-xAxis, .recharts-yAxis")) return false;
  const fw = Number.parseInt(window.getComputedStyle(src).fontWeight, 10);
  return Number.isFinite(fw) && fw >= 600;
}

function resolveExportTextFill(
  src: Element,
  plotBackground: string,
  theme: ResolvedChartAxisTheme
): string {
  const cs = window.getComputedStyle(src);
  const col = cs.fill || cs.color;
  const themed = isSvgAxisTitleText(src) ? theme.label : theme.tick;
  const resolved = resolveCssColorForExport(col || themed);
  return ensureReadableExportTextFill(resolved, plotBackground, {
    lightText: theme.tick,
    darkText: theme.label,
  });
}

function cloneSvgWithInlineStyles(
  source: SVGSVGElement,
  plotBackground: string,
  theme: ResolvedChartAxisTheme
): SVGSVGElement {
  const clone = source.cloneNode(true) as SVGSVGElement;
  const tagSel = "path,rect,circle,line,text,tspan,polygon,polyline,g";
  const srcEls = source.querySelectorAll(tagSel);
  const cloneEls = clone.querySelectorAll(tagSel);
  cloneEls.forEach((el, i) => {
    const src = srcEls[i];
    if (!src) return;
    const cs = window.getComputedStyle(src);
    const fill = cs.fill;
    const stroke = cs.stroke;
    if (fill && fill !== "none" && !fill.includes("rgba(0, 0, 0, 0)")) {
      el.setAttribute("fill", resolveCssColorForExport(fill));
    }
    if (stroke && stroke !== "none") {
      el.setAttribute("stroke", resolveCssColorForExport(stroke));
    }
    const sw = cs.strokeWidth;
    if (sw && sw !== "0px") el.setAttribute("stroke-width", sw);
    if (el.tagName === "text" || el.tagName === "tspan") {
      el.setAttribute("fill", resolveExportTextFill(src, plotBackground, theme));
      const fs = cs.fontSize;
      if (fs) el.setAttribute("font-size", fs);
      const ff = cs.fontFamily;
      if (ff) el.setAttribute("font-family", ff);
      const transform = cs.transform;
      if (transform && transform !== "none") {
        el.setAttribute("transform", transform);
      }
    }
  });
  return clone;
}

function tightenSvgViewBox(
  clone: SVGSVGElement,
  fallbackWidth: number,
  fallbackHeight: number,
  opts?: { minPadPx?: number }
): { width: number; height: number } {
  const minPad = opts?.minPadPx ?? 8;
  const mount = document.createElement("div");
  mount.style.cssText =
    "position:fixed;left:-9999px;top:0;visibility:hidden;pointer-events:none;overflow:visible;";
  document.body.appendChild(mount);
  mount.appendChild(clone);
  let width = fallbackWidth;
  let height = fallbackHeight;
  try {
    const bbox = clone.getBBox();
    if (bbox.width > 12 && bbox.height > 12) {
      const textNodes = [...clone.querySelectorAll("text")];
      let maxTextBottom = bbox.y + bbox.height;
      for (const text of textNodes) {
        try {
          const tb = text.getBBox();
          maxTextBottom = Math.max(maxTextBottom, tb.y + tb.height);
        } catch {
          // ignore detached text metrics
        }
      }
      const padX = minPad;
      const padTop = minPad;
      const padBottom = textNodes.length >= 4 ? minPad + 10 : minPad + 4;
      const x = bbox.x - padX;
      const y = bbox.y - padTop;
      const w = bbox.width + padX * 2;
      const h = Math.max(bbox.height, maxTextBottom - bbox.y) + padTop + padBottom;
      clone.setAttribute("viewBox", `${x} ${y} ${w} ${h}`);
      width = Math.max(1, Math.round(w));
      height = Math.max(1, Math.round(h));
    }
  } catch {
    // keep fallback viewBox
  } finally {
    mount.remove();
  }
  return { width, height };
}

function isRadialChartRoot(container: HTMLElement): boolean {
  return Boolean(container.querySelector(".recharts-pie-sector, .recharts-pie"));
}

function stripRadialLegendFromSvgClone(clone: SVGSVGElement): void {
  clone.querySelectorAll(".recharts-legend-wrapper").forEach((node) => {
    node.remove();
  });
}

type ExportLegendEntry = {
  label: string;
  color: string;
};

function extractRechartsLegendEntries(root: HTMLElement): ExportLegendEntry[] {
  const wrapper = root.querySelector(".recharts-legend-wrapper");
  if (!wrapper) return [];

  const entries: ExportLegendEntry[] = [];
  wrapper.querySelectorAll(".recharts-legend-item").forEach((item) => {
    const label =
      item.querySelector(".recharts-legend-item-text")?.textContent?.trim() ?? "";
    if (!label) return;

    const icon = item.querySelector("svg");
    const shape = icon?.querySelector("path, rect, circle");
    let color = "#6366f1";
    if (shape instanceof SVGElement) {
      color =
        shape.getAttribute("fill") ||
        window.getComputedStyle(shape).fill ||
        color;
    }
    entries.push({
      label,
      color: resolveCssColorForExport(color),
    });
  });
  return entries;
}

function renderLegendChromeToPng(
  entries: ExportLegendEntry[],
  exportWidth: number,
  scale: number,
  palette: ExportPalette
): { dataUrl: string; width: number; height: number } | null {
  if (!entries.length) return null;

  const fontFamily =
    'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';
  const labelFont = `500 ${RADIAL_EXPORT_LEGEND_FONT_PX}px ${fontFamily}`;
  const innerW = exportWidth - COMPOSITE_PAD_X * 2;
  const rowH = RADIAL_EXPORT_LEGEND_FONT_PX + RADIAL_EXPORT_LEGEND_ROW_EXTRA_PX;
  const rowGap = RADIAL_EXPORT_LEGEND_ITEM_GAP_PX;
  const swatch = RADIAL_EXPORT_LEGEND_ICON_PX;
  const swatchGap = RADIAL_EXPORT_LEGEND_SWATCH_GAP_PX;

  const probe = document.createElement("canvas");
  const pctx = probe.getContext("2d");
  if (!pctx) return null;

  const itemWidths = entries.map((entry) => {
    pctx.font = labelFont;
    return swatch + swatchGap + pctx.measureText(entry.label).width + 16;
  });
  const totalOneRow =
    itemWidths.reduce((a, b) => a + b, 0) + rowGap * (entries.length - 1);

  const rows: ExportLegendEntry[][] = [];
  if (totalOneRow <= innerW) {
    rows.push(entries);
  } else {
    let current: ExportLegendEntry[] = [];
    let rowW = 0;
    entries.forEach((entry, i) => {
      const w = itemWidths[i] ?? 0;
      const gap = current.length > 0 ? rowGap : 0;
      if (current.length > 0 && rowW + gap + w > innerW) {
        rows.push(current);
        current = [entry];
        rowW = w;
      } else {
        current.push(entry);
        rowW += gap + w;
      }
    });
    if (current.length) rows.push(current);
  }

  const contentH =
    rows.length * rowH + Math.max(0, rows.length - 1) * rowGap + 14;

  const canvas = document.createElement("canvas");
  canvas.width = exportWidth * scale;
  canvas.height = contentH * scale;
  const ctx = canvas.getContext("2d");
  if (!ctx) return null;

  ctx.scale(scale, scale);
  ctx.fillStyle = palette.background;
  ctx.fillRect(0, 0, exportWidth, contentH);

  let y = 4;
  for (const row of rows) {
    const widths = row.map((entry) => {
      ctx.font = labelFont;
      return swatch + swatchGap + ctx.measureText(entry.label).width + 16;
    });
    const totalW =
      widths.reduce((a, b) => a + b, 0) + rowGap * (row.length - 1);
    let x = (exportWidth - totalW) / 2;

    row.forEach((entry, i) => {
      const w = widths[i] ?? 0;
      ctx.fillStyle = entry.color;
      ctx.beginPath();
      ctx.arc(x + swatch / 2, y + rowH / 2, swatch / 2, 0, Math.PI * 2);
      ctx.fill();

      ctx.font = labelFont;
      ctx.fillStyle = palette.chipValue;
      ctx.textAlign = "left";
      ctx.textBaseline = "middle";
      ctx.fillText(entry.label, x + swatch + swatchGap, y + rowH / 2);
      x += w + rowGap;
    });
    y += rowH + rowGap;
  }

  return {
    dataUrl: canvas.toDataURL("image/png"),
    width: exportWidth,
    height: contentH,
  };
}

/** Marks export roots so charts disable Recharts animation before capture. */
export const CHART_PNG_CAPTURE_ATTR = "data-chart-png-capture";

function nextFrame(): Promise<void> {
  return new Promise((resolve) => requestAnimationFrame(() => resolve()));
}

/** Wait until a line/area path stops changing (animation settled) or timeout. */
export async function waitForStableChartSvg(
  root: HTMLElement,
  maxMs = 900
): Promise<void> {
  if (typeof window === "undefined") return;

  const deadline = Date.now() + maxMs;
  let stableFrames = 0;
  let prevPath = "";

  while (Date.now() < deadline) {
    const curve = root.querySelector(
      ".recharts-line-curve, .recharts-area-curve"
    );
    if (!curve) {
      stableFrames = 0;
      await nextFrame();
      continue;
    }
    const d = curve.getAttribute("d") ?? "";
    if (d.length > 16 && d === prevPath) {
      stableFrames += 1;
      if (stableFrames >= 2) break;
    } else {
      stableFrames = 0;
      prevPath = d;
    }
    await nextFrame();
  }

  await new Promise<void>((resolve) => window.setTimeout(resolve, 120));
}

/** Reflow Recharts after layout changes (e.g. sidebar collapse) before PNG capture. */
export async function prepareChartForPngCapture(
  sourceRoot: HTMLElement
): Promise<void> {
  if (typeof window === "undefined") return;

  sourceRoot.setAttribute(CHART_PNG_CAPTURE_ATTR, "1");

  window.dispatchEvent(new Event("resize"));
  await nextFrame();
  await nextFrame();

  const plotRoot = resolvePlotRoot(sourceRoot);
  const rect = plotRoot.getBoundingClientRect();
  const width = Math.max(1, Math.floor(rect.width || plotRoot.clientWidth));
  const height = Math.max(1, Math.floor(rect.height || plotRoot.clientHeight));
  plotRoot.style.width = `${width}px`;
  if (height > 1) plotRoot.style.height = `${height}px`;

  await new Promise<void>((resolve) => window.setTimeout(resolve, 160));
  window.dispatchEvent(new Event("resize"));
  await nextFrame();
  await nextFrame();
  await waitForStableChartSvg(sourceRoot);
}

async function renderPlotSvgToPng(
  container: HTMLElement,
  scale: number,
  targetPlotWidth: number | undefined,
  plotBackground: string
): Promise<{ dataUrl: string; width: number; height: number } | null> {
  const plotRoot = resolvePlotRoot(container);
  const svg = findPrimaryChartSvg(plotRoot);
  if (!svg) return null;

  const rect = svg.getBoundingClientRect();
  let width = Math.max(1, Math.round(rect.width));
  let height = Math.max(1, Math.round(rect.height));
  if (width <= 2 || height <= 2) {
    const pr = plotRoot.getBoundingClientRect();
    width = Math.max(pr.width || plotRoot.clientWidth || 720, 1);
    height = Math.max(pr.height || plotRoot.clientHeight || 320, 1);
  }

  const plotBox = plotRoot.getBoundingClientRect();
  if (width < 320 && plotBox.width > width) {
    width = Math.max(width, Math.round(Math.min(plotBox.width, 960)));
    height = Math.max(height, Math.round(Math.min(plotBox.height, 540)));
  }

  const axisTheme = readResolvedChartAxisTheme(container);
  const clone = cloneSvgWithInlineStyles(svg, plotBackground, axisTheme);
  applyPngExportSvgPolish(clone, {
    darkBackground: isDarkExportBackground(plotBackground),
  });
  const radialExport = isRadialChartRoot(container);
  if (radialExport) {
    stripRadialLegendFromSvgClone(clone);
  }
  const tightened = tightenSvgViewBox(clone, width, height, {
    minPadPx: radialExport ? RADIAL_EXPORT_MIN_SVG_PAD_PX : 4,
  });
  width = tightened.width;
  height = tightened.height;

  if (targetPlotWidth && targetPlotWidth > width) {
    const boost = Math.min(targetPlotWidth / width, 1.22);
    width = Math.round(width * boost);
    height = Math.round(height * boost);
  }

  clone.setAttribute("width", String(width));
  clone.setAttribute("height", String(height));
  clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
  if (!clone.getAttribute("viewBox")) {
    clone.setAttribute("viewBox", `0 0 ${width} ${height}`);
  }
  clone.setAttribute("preserveAspectRatio", "xMidYMid meet");
  clone.setAttribute("overflow", "visible");

  const svgString = new XMLSerializer().serializeToString(clone);
  const canvas = document.createElement("canvas");
  canvas.width = width * scale;
  canvas.height = height * scale;
  const ctx = canvas.getContext("2d");
  if (!ctx) return null;
  ctx.fillStyle = plotBackground;
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.setTransform(scale, 0, 0, scale, 0, 0);

  const v = await Canvg.fromString(ctx, svgString);
  await v.render();
  return {
    dataUrl: canvas.toDataURL("image/png"),
    width,
    height,
  };
}

type ExportChip = {
  label: string;
  value: string;
  mono?: boolean;
  emphasis?: "change" | "default";
};

type ExportReasonBlock = {
  label: string;
  body: string;
};

function parseReasonFromNote(note: Element | null): ExportReasonBlock | null {
  if (!note) return null;

  const spans = [...note.querySelectorAll(":scope > span")];
  let label = spans[0]?.textContent?.trim() ?? "";
  let body = spans[1]?.textContent?.trim() ?? "";

  if (!body) {
    const raw = note.textContent?.trim().replace(/\s+/g, " ") ?? "";
    if (!raw) return null;
    const prefix = raw.match(/^why this chart\s*(?:[·•:—-]\s*)?/i);
    if (prefix) {
      label = label || "Why this chart";
      body = raw.slice(prefix[0].length).trim();
    } else {
      body = raw;
    }
  }

  if (!label && body) label = "Why this chart";
  if (!body) return null;

  return { label, body };
}

function extractRateQualityWarning(sourceRoot: HTMLElement): string {
  const el = sourceRoot.querySelector(".chart-rate-quality-warning");
  return el?.textContent?.trim() ?? "";
}

function classifyOverviewInsightChipEmphasis(): "default" {
  return "default";
}

function extractOverviewInsightChips(sourceRoot: HTMLElement): ExportChip[] {
  const chips: ExportChip[] = [];
  const row = sourceRoot.querySelector(".overview-dash-insight-chips");
  if (!row) return chips;
  row.querySelectorAll(":scope > span").forEach((span) => {
    const text = span.textContent?.trim();
    if (text) {
      chips.push({
        label: "",
        value: text,
        mono: true,
        emphasis: classifyOverviewInsightChipEmphasis(),
      });
    }
  });
  return chips;
}

function findExportHeaderZone(sourceRoot: HTMLElement): HTMLElement | null {
  const sticky = sourceRoot.querySelector(".charts-tab-preview-header-sticky");
  if (sticky instanceof HTMLElement) return sticky;
  const overview = sourceRoot.querySelector(".overview-png-export-header");
  if (overview instanceof HTMLElement) return overview;
  return null;
}

function extractStructuredMetadataChips(
  header: HTMLElement
): ExportChip[] {
  const row = header.querySelector("[data-chart-metadata-chips]");
  if (!row) return [];
  const chips: ExportChip[] = [];
  row.querySelectorAll("[data-chart-metadata-chip]").forEach((el) => {
    const kind = el.getAttribute("data-chip-kind");
    if (kind === "mono" || kind === "lead") {
      const value = el.textContent?.trim() ?? "";
      if (value) {
        chips.push({
          label: "",
          value,
          mono: true,
        });
      }
      return;
    }
    const parts = [...el.querySelectorAll(":scope > span")];
    if (parts.length >= 2) {
      chips.push({
        label: parts[0]?.textContent?.trim() ?? "",
        value: parts[1]?.textContent?.trim() ?? "",
      });
    }
  });
  return chips;
}

function extractHeaderContent(
  header: HTMLElement,
  sourceRoot?: HTMLElement
): {
  kicker: string;
  title: string;
  subtitle: string;
  qualityWarning: string;
  chips: ExportChip[];
  reason: ExportReasonBlock | null;
} {
  const kicker =
    header.querySelector("[class*='viz-kicker']")?.textContent?.trim() ?? "";
  const title = header.querySelector("h3")?.textContent?.trim() ?? "";
  const subtitle =
    header.querySelector("[class*='viz-subtitle']")?.textContent?.trim() ?? "";

  let chips = extractStructuredMetadataChips(header);
  if (!chips.length) {
    const chipsRow = header.querySelector(
      "[class*='viz-chips'] > div, [class*='VizChips'] > div, [data-chart-metadata-chips]"
    );
    if (chipsRow) {
      chipsRow.querySelectorAll(":scope > span").forEach((span) => {
        const parts = [...span.querySelectorAll(":scope > span")];
        if (span.classList.contains("items-center") && parts.length >= 2) {
          chips.push({
            label: parts[0]?.textContent?.trim() ?? "",
            value: parts[1]?.textContent?.trim() ?? "",
          });
          return;
        }
        const text = span.textContent?.trim();
        if (text) chips.push({ label: "", value: text, mono: true });
      });
    }
  }

  if (!chips.length && sourceRoot) {
    chips.push(...extractOverviewInsightChips(sourceRoot));
  }

  const qualityWarning = sourceRoot
    ? extractRateQualityWarning(sourceRoot)
    : "";

  const reason = parseReasonFromNote(header.querySelector("[role='note']"));

  return { kicker, title, subtitle, qualityWarning, chips, reason };
}

function measureTextWidth(
  ctx: CanvasRenderingContext2D,
  text: string,
  font: string
): number {
  ctx.font = font;
  return ctx.measureText(text).width;
}

function wrapTextLines(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
  font: string
): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  const lines: string[] = [];
  let line = words[0]!;
  for (let i = 1; i < words.length; i++) {
    const next = `${line} ${words[i]}`;
    if (measureTextWidth(ctx, next, font) <= maxWidth) {
      line = next;
    } else {
      lines.push(line);
      line = words[i]!;
    }
  }
  lines.push(line);
  return lines;
}

function measureChipWidth(
  ctx: CanvasRenderingContext2D,
  chip: ExportChip,
  chipLabelFont: string,
  chipValueFont: string
): number {
  if (chip.mono) {
    return measureTextWidth(ctx, chip.value, chipValueFont) + CHIP_PAD_X * 2 + 4;
  }
  return (
    measureTextWidth(ctx, chip.label, chipLabelFont) +
    measureTextWidth(ctx, chip.value, chipValueFont) +
    CHIP_PAD_X * 2 +
    CHIP_INNER_GAP +
    4
  );
}

function layoutChipRows(
  ctx: CanvasRenderingContext2D,
  chips: ExportChip[],
  innerW: number,
  chipLabelFont: string,
  chipValueFont: string,
  chipRowGapPx: number = CHIP_ROW_GAP
): { rows: ExportChip[][]; rowHeights: number[] } {
  if (!chips.length) return { rows: [], rowHeights: [] };

  const widths = chips.map((c) =>
    measureChipWidth(ctx, c, chipLabelFont, chipValueFont)
  );
  const totalOneRow =
    widths.reduce((a, b) => a + b, 0) +
    chipRowGapPx * (chips.length - 1);

  if (totalOneRow <= innerW) {
    return { rows: [chips], rowHeights: [CHIP_H] };
  }

  const rows: ExportChip[][] = [[]];
  const rowHeights: number[] = [CHIP_H];
  let rowW = 0;
  for (let i = 0; i < chips.length; i++) {
    const chip = chips[i]!;
    const w = widths[i]!;
    const currentRow = rows[rows.length - 1]!;
    const gap = currentRow.length > 0 ? chipRowGapPx : 0;
    if (currentRow.length > 0 && rowW + gap + w > innerW) {
      rows.push([chip]);
      rowHeights.push(CHIP_H);
      rowW = w;
    } else {
      currentRow.push(chip);
      rowW += gap + w;
    }
  }
  return { rows, rowHeights };
}

function shouldUseOverviewSummaryChipSpacing(
  content: ReturnType<typeof extractHeaderContent>
): boolean {
  const chips = content.chips;
  if (chips.length !== 3) return false;
  if (!chips.every((c) => c.mono)) return false;

  // Overview mini PNG uses values like:
  // "Top: …", "Lowest: …", "Gap/Change: …", or trend "Start/Latest/Change"
  return chips.every((c) => {
    const v = String(c.value ?? "").trim().toLowerCase();
    return (
      v.startsWith("top:") ||
      v.startsWith("lowest:") ||
      v.startsWith("gap:") ||
      v.startsWith("change:") ||
      v.startsWith("start ") ||
      v.startsWith("latest ")
    );
  });
}

type HeaderLayout = {
  exportWidth: number;
  contentH: number;
  innerW: number;
  qualityWarningLines: string[];
  reasonLabel: string;
  reasonBodyLines: string[];
  chipRows: ExportChip[][];
  chipRowHeights: number[];
  chipRowGapPx: number;
};

function layoutHeaderExport(
  ctx: CanvasRenderingContext2D,
  content: ReturnType<typeof extractHeaderContent>,
  sourceWidth: number
): HeaderLayout {
  const exportWidth = Math.max(Math.round(sourceWidth), EXPORT_MIN_WIDTH);
  const innerW = exportWidth - COMPOSITE_PAD_X * 2;
  const chipRowGapPx = shouldUseOverviewSummaryChipSpacing(content)
    ? OVERVIEW_SUMMARY_CHIP_ROW_GAP
    : CHIP_ROW_GAP;

  const fontFamily =
    'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';
  const chipLabelFont = `600 ${CHIP_LABEL_FONT_SIZE_PX}px ${fontFamily}`;
  const chipValueFont = `500 ${CHIP_VALUE_FONT_SIZE_PX}px ${fontFamily}`;
  const reasonFont = `400 13px ${fontFamily}`;

  const { rows: chipRows, rowHeights } = layoutChipRows(
    ctx,
    content.chips,
    innerW,
    chipLabelFont,
    chipValueFont,
    chipRowGapPx
  );

  const reasonLabel = content.reason?.label ?? "";
  const reasonBodyLines = content.reason?.body
    ? wrapTextLines(ctx, content.reason.body, innerW - 4, reasonFont)
    : [];
  const qualityWarningFont = `500 ${QUALITY_WARNING_FONT_SIZE_PX}px ${fontFamily}`;
  const qualityWarningLines = content.qualityWarning
    ? wrapTextLines(ctx, content.qualityWarning, innerW - 4, qualityWarningFont)
    : [];

  let contentH = HEADER_PAD_Y;
  if (content.kicker) contentH += 13 + GAP_AFTER_KICKER;
  if (content.title) {
    contentH += 26 + (content.chips.length ? GAP_AFTER_TITLE_WITH_CHIPS : GAP_AFTER_TITLE);
  }
  if (content.subtitle) contentH += 18 + GAP_AFTER_SUBTITLE;

  if (qualityWarningLines.length) {
    contentH += qualityWarningLines.length * 16 + 6;
  }

  if (chipRows.length) {
    contentH += rowHeights.reduce((a, h) => a + h, 0);
    contentH += chipRowGapPx * Math.max(0, chipRows.length - 1);
    contentH += GAP_AFTER_CHIPS;
  }

  if (reasonLabel || reasonBodyLines.length) {
    if (reasonLabel) {
      contentH += REASON_LABEL_LINE_H + REASON_LABEL_BODY_GAP;
    }
    contentH += reasonBodyLines.length * REASON_LINE_H;
    contentH += REASON_BOTTOM_PAD;
  }

  contentH += HEADER_PAD_Y;

  return {
    exportWidth,
    contentH,
    innerW,
    qualityWarningLines,
    reasonLabel,
    reasonBodyLines,
    chipRows,
    chipRowHeights: rowHeights,
    chipRowGapPx,
  };
}

function renderHeaderChromeToPng(
  sourceRoot: HTMLElement,
  scale: number,
  palette: ExportPalette,
  layoutWidthPx?: number
): { dataUrl: string; width: number; height: number } | null {
  const header = findExportHeaderZone(sourceRoot);
  if (!header) return null;

  const content = extractHeaderContent(header, sourceRoot);
  if (!content.title && !content.chips.length && !content.reason) return null;

  const fontFamily =
    'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';
  const kickerFont = `600 11px ${fontFamily}`;
  const titleFont = `600 24px ${fontFamily}`;
  const subtitleFont = `400 14px ${fontFamily}`;
  const chipLabelFont = `600 ${CHIP_LABEL_FONT_SIZE_PX}px ${fontFamily}`;
  const chipValueFont = `500 ${CHIP_VALUE_FONT_SIZE_PX}px ${fontFamily}`;
  const reasonLabelFont = `600 11px ${fontFamily}`;
  const reasonFont = `400 13px ${fontFamily}`;
  const qualityWarningFont = `500 ${QUALITY_WARNING_FONT_SIZE_PX}px ${fontFamily}`;

  const probe = document.createElement("canvas");
  const pctx = probe.getContext("2d");
  if (!pctx) return null;

  const measuredW = Math.round(sourceRoot.getBoundingClientRect().width);
  const layout = layoutHeaderExport(
    pctx,
    content,
    layoutWidthPx ?? Math.max(measuredW, EXPORT_MIN_WIDTH)
  );

  const canvas = document.createElement("canvas");
  canvas.width = layout.exportWidth * scale;
  canvas.height = Math.max(72, layout.contentH) * scale;
  const ctx = canvas.getContext("2d");
  if (!ctx) return null;

  ctx.scale(scale, scale);
  // Transparent header layer — card inner fill shows through from composite.

  let y = HEADER_PAD_Y;
  const centerX = layout.exportWidth / 2;

  if (content.kicker) {
    ctx.font = kickerFont;
    ctx.fillStyle = palette.kicker;
    ctx.textAlign = "center";
    ctx.textBaseline = "top";
    ctx.fillText(content.kicker.toUpperCase(), centerX, y);
    y += 13 + GAP_AFTER_KICKER;
  }

  if (content.title) {
    ctx.font = titleFont;
    ctx.fillStyle = palette.title;
    ctx.textAlign = "center";
    ctx.textBaseline = "top";
    ctx.fillText(content.title, centerX, y);
    y += 26 + (content.chips.length ? GAP_AFTER_TITLE_WITH_CHIPS : GAP_AFTER_TITLE);
  }

  if (content.subtitle) {
    ctx.font = subtitleFont;
    ctx.fillStyle = palette.subtitle;
    ctx.textAlign = "center";
    ctx.textBaseline = "top";
    ctx.fillText(content.subtitle, centerX, y);
    y += 18 + GAP_AFTER_SUBTITLE;
  }

  if (layout.qualityWarningLines.length) {
    ctx.font = qualityWarningFont;
    ctx.fillStyle = palette.warningNote;
    ctx.textAlign = "center";
    ctx.textBaseline = "top";
    ctx.globalAlpha = 0.92;
    for (const line of layout.qualityWarningLines) {
      ctx.fillText(line, centerX, y);
      y += 16;
    }
    ctx.globalAlpha = 1;
    y += 6;
  }

  for (let ri = 0; ri < layout.chipRows.length; ri++) {
    const row = layout.chipRows[ri]!;
    const chipWidths = row.map((chip) =>
      measureChipWidth(ctx, chip, chipLabelFont, chipValueFont)
    );
    const totalW =
      chipWidths.reduce((a, b) => a + b, 0) +
      layout.chipRowGapPx * (row.length - 1);
    let x = centerX - totalW / 2;
    for (let i = 0; i < row.length; i++) {
      const chip = row[i]!;
      const w = chipWidths[i]!;
      ctx.fillStyle = palette.chipBg;
      ctx.strokeStyle = palette.chipBorder;
      ctx.lineWidth = 1;
      roundRect(ctx, x, y, w, CHIP_H, 8);
      ctx.fill();
      ctx.stroke();

      let tx = x + CHIP_PAD_X;
      const ty = y + (CHIP_H - CHIP_VALUE_FONT_SIZE_PX) / 2;
      if (chip.label && !chip.mono) {
        ctx.font = chipLabelFont;
        ctx.fillStyle = palette.chipLabel;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        ctx.fillText(chip.label, tx, ty);
        tx += measureTextWidth(ctx, chip.label, chipLabelFont) + CHIP_INNER_GAP;
      }
      ctx.font = chipValueFont;
      ctx.fillStyle = palette.chipValue;
      // Ensure mono chips (Overview Top/Lowest/Gap) render inside pill bounds.
      // Without this, title-phase center alignment can leak into chip text draw.
      ctx.textAlign = "left";
      ctx.textBaseline = "top";
      ctx.fillText(chip.value, tx, ty);
      x += w + layout.chipRowGapPx;
    }
    y += layout.chipRowHeights[ri] ?? CHIP_H;
    if (ri < layout.chipRows.length - 1) y += layout.chipRowGapPx;
  }

  if (layout.chipRows.length) y += GAP_AFTER_CHIPS;

  if (layout.reasonLabel || layout.reasonBodyLines.length) {
    ctx.textAlign = "center";
    ctx.textBaseline = "top";

    if (layout.reasonLabel) {
      ctx.font = reasonLabelFont;
      ctx.fillStyle = palette.kicker;
      ctx.fillText(layout.reasonLabel.toUpperCase(), centerX, y);
      y += REASON_LABEL_LINE_H + REASON_LABEL_BODY_GAP;
    }

    ctx.font = reasonFont;
    ctx.fillStyle = palette.reason;
    for (const line of layout.reasonBodyLines) {
      ctx.fillText(line, centerX, y);
      y += REASON_LINE_H;
    }
    y += REASON_BOTTOM_PAD;
  }

  return {
    dataUrl: canvas.toDataURL("image/png"),
    width: layout.exportWidth,
    height: Math.max(1, Math.round(layout.contentH)),
  };
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number
): void {
  const radius = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + w, y, x + w, y + h, radius);
  ctx.arcTo(x + w, y + h, x, y + h, radius);
  ctx.arcTo(x, y + h, x, y, radius);
  ctx.arcTo(x, y, x + w, y, radius);
  ctx.closePath();
}

function loadImage(dataUrl: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("Failed to load capture image."));
    img.src = dataUrl;
  });
}

function resolveCardSurfacePalette(palette: ExportPalette): {
  outer: string;
  inner: string;
  border: string;
  shadow: string;
} {
  const dark =
    palette.background === "#0f172a" || palette.background === "#0b1220";
  if (dark) {
    return {
      outer: "#0b1220",
      inner: "#111827",
      border: "#475569",
      shadow: "rgba(0, 0, 0, 0.42)",
    };
  }
  return {
    outer: "#f1f5f9",
    inner: "#ffffff",
    border: "#cbd5e1",
    shadow: "rgba(15, 23, 42, 0.14)",
  };
}

function drawExportCardFill(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  surfaces: ReturnType<typeof resolveCardSurfacePalette>
): void {
  ctx.save();
  ctx.shadowColor = surfaces.shadow;
  ctx.shadowBlur = 28;
  ctx.shadowOffsetY = 10;
  ctx.fillStyle = surfaces.inner;
  roundRect(ctx, x, y, w, h, EXPORT_CARD_RADIUS);
  ctx.fill();
  ctx.restore();
}

/** Stroke the card frame last so header/plot layers never cover the rounded border. */
function drawExportCardBorder(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  surfaces: ReturnType<typeof resolveCardSurfacePalette>
): void {
  const inset = EXPORT_CARD_BORDER / 2;
  ctx.save();
  ctx.strokeStyle = surfaces.border;
  ctx.lineWidth = EXPORT_CARD_BORDER;
  roundRect(
    ctx,
    x + inset,
    y + inset,
    w - EXPORT_CARD_BORDER,
    h - EXPORT_CARD_BORDER,
    Math.max(0, EXPORT_CARD_RADIUS - inset)
  );
  ctx.stroke();
  ctx.restore();
}

function clipExportCardContent(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number
): void {
  const inset = EXPORT_CARD_BORDER;
  roundRect(
    ctx,
    x + inset,
    y + inset,
    w - inset * 2,
    h - inset * 2,
    Math.max(0, EXPORT_CARD_RADIUS - inset)
  );
  ctx.clip();
}

function drawExportFooter(
  ctx: CanvasRenderingContext2D,
  cardX: number,
  cardY: number,
  cardW: number,
  cardH: number,
  footerText: string,
  palette: ExportPalette,
  fontPx: number = EXPORT_FOOTER_FONT_PX,
  padBottom: number = EXPORT_FOOTER_PAD_BOTTOM
): void {
  const fontFamily =
    'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';
  ctx.font = `500 ${fontPx}px ${fontFamily}`;
  ctx.fillStyle = palette.footer;
  ctx.textAlign = "center";
  ctx.textBaseline = "bottom";
  ctx.globalAlpha = 1;
  ctx.fillText(
    footerText,
    cardX + cardW / 2,
    cardY + cardH - padBottom
  );
  ctx.globalAlpha = 1;
}

async function compositeExportPng(
  header: { dataUrl: string; width: number; height: number } | null,
  plot: { dataUrl: string; width: number; height: number },
  legend: { dataUrl: string; width: number; height: number } | null,
  scale: number,
  palette: ExportPalette,
  canvasSize?: { width: number; height: number },
  footerText: string = EXPORT_FOOTER_TEXT,
  radialExport = false
): Promise<{ dataUrl: string; width: number; height: number }> {
  const plotImg = await loadImage(plot.dataUrl);
  const headerImg = header ? await loadImage(header.dataUrl) : null;
  const legendImg = legend ? await loadImage(legend.dataUrl) : null;

  const headerW = headerImg ? headerImg.naturalWidth : 0;
  const headerH = headerImg ? headerImg.naturalHeight : 0;
  const legendW = legendImg ? legendImg.naturalWidth : 0;
  const legendH = legendImg ? legendImg.naturalHeight : 0;

  const contentW = Math.max(
    plotImg.naturalWidth,
    headerW,
    legendW,
    Math.round((header?.width ?? plot.width) * scale)
  );

  const cardInnerW = contentW - EXPORT_CARD_PAD * 2;
  const plotNaturalW = plotImg.naturalWidth;
  const plotNaturalH = plotImg.naturalHeight;
  const plotWidthUtil = radialExport
    ? RADIAL_EXPORT_PLOT_WIDTH_UTIL
    : plotNaturalW < cardInnerW * 0.78
      ? PLOT_WIDTH_UTIL_COMPACT
      : PLOT_WIDTH_UTIL;
  const targetPlotW = Math.round(cardInnerW * plotWidthUtil);
  const plotScale = targetPlotW / plotNaturalW;
  const plotW = Math.round(plotNaturalW * plotScale);
  const plotH = Math.round(plotNaturalH * plotScale);

  const legendGap =
    legendH > 0
      ? radialExport
        ? RADIAL_EXPORT_LEGEND_PLOT_GAP_PX
        : 8
      : 0;
  const footerReserve = radialExport
    ? RADIAL_EXPORT_FOOTER_RESERVE_PX
    : EXPORT_FOOTER_H;
  const contentH =
    EXPORT_CARD_PAD +
    headerH +
    (headerH > 0 ? HEADER_PLOT_GAP : 0) +
    plotH +
    legendGap +
    legendH +
    EXPORT_CARD_PAD +
    footerReserve;

  const outW = canvasSize?.width
    ? Math.round(canvasSize.width * scale)
    : Math.max(contentW, Math.round(EXPORT_MIN_WIDTH * scale));
  const fixedOutH = canvasSize?.height
    ? Math.round(canvasSize.height * scale)
    : contentH;
  const outH = Math.max(fixedOutH, contentH);

  const canvas = document.createElement("canvas");
  canvas.width = outW;
  canvas.height = outH;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Unable to create export canvas.");

  const surfaces = resolveCardSurfacePalette(palette);
  ctx.fillStyle = surfaces.outer;
  ctx.fillRect(0, 0, outW, outH);

  const cardW = Math.min(contentW, outW - COMPOSITE_PAD_X * 2);
  const cardH = Math.min(contentH, outH - COMPOSITE_PAD_Y * 2);
  const cardX = Math.round((outW - cardW) / 2);
  const minCardY = COMPOSITE_PAD_Y + EXPORT_CARD_BORDER;
  const cardY = Math.max(minCardY, Math.round((outH - cardH) / 2));

  drawExportCardFill(ctx, cardX, cardY, cardW, cardH, surfaces);

  ctx.save();
  clipExportCardContent(ctx, cardX, cardY, cardW, cardH);

  let y = cardY + EXPORT_CARD_PAD;
  const centerX = cardX + cardW / 2;

  if (headerImg && headerH > 0) {
    const hx = Math.round(centerX - headerW / 2);
    ctx.drawImage(headerImg, hx, y, headerW, headerH);
    y += headerH + HEADER_PLOT_GAP;
  }

  const px = Math.round(centerX - plotW / 2);
  ctx.drawImage(plotImg, px, y, plotW, plotH);
  y += plotH;

  if (legendImg && legendH > 0) {
    y += legendGap;
    const lx = Math.round(centerX - legendW / 2);
    ctx.drawImage(legendImg, lx, y, legendW, legendH);
  }

  ctx.restore();

  drawExportFooter(
    ctx,
    cardX,
    cardY,
    cardW,
    cardH,
    footerText,
    palette,
    radialExport ? RADIAL_EXPORT_FOOTER_FONT_PX : EXPORT_FOOTER_FONT_PX,
    radialExport ? 18 : EXPORT_FOOTER_PAD_BOTTOM
  );
  drawExportCardBorder(ctx, cardX, cardY, cardW, cardH, surfaces);

  return {
    dataUrl: canvas.toDataURL("image/png"),
    width: Math.max(1, Math.round(outW / scale)),
    height: Math.max(1, Math.round(outH / scale)),
  };
}

export type CaptureElementPngOptions = {
  scale?: number;
  backgroundColor?: string;
  ignoreElement?: (el: Element) => boolean;
  /** Fixed composite width (e.g. 1400px presentation export). */
  layoutWidthPx?: number;
  /** Fixed presentation card canvas (title + plot + chips). */
  canvasWidthPx?: number;
  canvasHeightPx?: number;
  /** Optional footer line (defaults to app branding). */
  footerText?: string;
};

/** Build export footer — app branding only (no uploaded filenames). */
export function buildPngExportFooterText(_datasetName?: string | null): string {
  return EXPORT_FOOTER_TEXT;
}

/**
 * Charts tab export: title + chips (canvas) + chart (Canvg), presentation scale.
 */
export async function captureElementToPng(
  sourceRoot: HTMLElement,
  options: CaptureElementPngOptions = {}
): Promise<{ dataUrl: string; width: number; height: number }> {
  const scale = options.scale ?? 3;
  const backgroundColor = resolveExportBackground(options.backgroundColor);
  const palette = resolveExportPalette(backgroundColor);

  try {
    await prepareChartForPngCapture(sourceRoot);
  } finally {
    sourceRoot.removeAttribute(CHART_PNG_CAPTURE_ATTR);
  }

  const measured = Math.round(sourceRoot.getBoundingClientRect().width);
  const exportWidth = options.layoutWidthPx
    ? options.layoutWidthPx
    : Math.max(measured, EXPORT_MIN_WIDTH);
  const targetPlotWidth = Math.round(
    (exportWidth - COMPOSITE_PAD_X * 2) * PLOT_WIDTH_UTIL
  );

  const plot = await renderPlotSvgToPng(
    sourceRoot,
    scale,
    targetPlotWidth,
    palette.background
  );
  if (!plot?.dataUrl) {
    throw new Error("Chart is not available to download.");
  }

  let header: { dataUrl: string; width: number; height: number } | null = null;
  try {
    header = renderHeaderChromeToPng(sourceRoot, scale, palette, exportWidth);
  } catch (err) {
    console.warn("Charts tab header PNG capture skipped:", err);
  }

  let legend: { dataUrl: string; width: number; height: number } | null = null;
  try {
    const entries = extractRechartsLegendEntries(sourceRoot);
    legend = renderLegendChromeToPng(entries, exportWidth, scale, palette);
  } catch (err) {
    console.warn("Chart legend PNG capture skipped:", err);
  }

  const canvasSize =
    options.canvasWidthPx && options.canvasHeightPx
      ? { width: options.canvasWidthPx, height: options.canvasHeightPx }
      : undefined;

  const footerText =
    options.footerText ?? buildPngExportFooterText();

  const radialExport = isRadialChartRoot(sourceRoot);

  return compositeExportPng(
    header,
    plot,
    legend,
    scale,
    palette,
    canvasSize,
    footerText,
    radialExport
  );
}

/** True when an export root is the dedicated offscreen portal (not the visible card). */
export function isOffscreenPngExportRoot(root: HTMLElement): boolean {
  return root.getAttribute("data-chart-png-offscreen") === "1";
}
