import { describe, expect, it } from "vitest";
import {
  buildPngExportFooterText,
  CHART_PNG_CAPTURE_ATTR,
  isOffscreenPngExportRoot,
  prepareChartForPngCapture,
  waitForStableChartSvg,
} from "@/lib/chart-png-capture";

describe("chart PNG capture helpers", () => {
  it("exports capture attribute for chart renderers", () => {
    expect(CHART_PNG_CAPTURE_ATTR).toBe("data-chart-png-capture");
  });

  it("prepareChartForPngCapture no-ops in non-browser environments", async () => {
    await expect(
      prepareChartForPngCapture({} as HTMLElement)
    ).resolves.toBeUndefined();
  });

  it("waitForStableChartSvg no-ops in non-browser environments", async () => {
    await expect(waitForStableChartSvg({} as HTMLElement)).resolves.toBeUndefined();
  });

  it("builds export footer with optional dataset name", () => {
    expect(buildPngExportFooterText()).toBe("Generated by AI Analytics");
    expect(buildPngExportFooterText("sales.csv")).toBe(
      "Generated by AI Analytics · sales.csv"
    );
  });

  it("distinguishes offscreen export roots from visible chart cards", () => {
    if (typeof document === "undefined") return;
    const visible = document.createElement("div");
    const offscreen = document.createElement("div");
    offscreen.setAttribute("data-chart-png-offscreen", "1");
    expect(isOffscreenPngExportRoot(visible)).toBe(false);
    expect(isOffscreenPngExportRoot(offscreen)).toBe(true);
  });
});
